config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins, :skip => [:registrations]
  resources :posts

  root :to => "posts#index"

  get 'about', :to => 'statics#about'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 4, :order => "created_at DESC")

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
def about
end

def contact
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>All Things Evaluated by A K McCrate</title>
  <%= stylesheet_link_tag    "application", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <header id="titles">
    <h1 class="title"><a href="/">All Things Evaluated</a></h1>
    <h2 class="byline">By <a href="/about">A K McCrate</a></h2>
  </header>

  <% if admin_signed_in? %>
  <ul class="admin-options">
      <li><%= link_to '★ New Post', new_post_path %></li>
      <li><%= link_to '★ Sign Out', destroy_admin_session_path, :method => :delete %></li>
  </ul>
  <% end %>

  <section id="posts">
    <%= yield %>
  </section>

  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    
    <% @posts.each do |post| %>
    <article>

        <h1><%= link_to post.title, post%></h1>
        <div class="date"><%= post.created_at.strftime("%B %d, %Y")%></div>

        <%= simple_format(post.body) %>

        <% if admin_signed_in? %>
        <span class="admin">

          <%= link_to 'Edit', edit_post_path(post) %> |
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Now wait a minute. Are you sure this is what you\'re trying to do?' } %>
        </span>
        <% end %>


      </article>
    <% end %>

      <%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>What's this shit?</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<article>
<h1><%= @post.title %></h1>
<div class="date"><%= @post.created_at.strftime("%B %d, %Y")%></div>
<p><%= simple_format(@post.body) %></p>
<div class="back-button"><%= link_to 'Back Home', posts_path %></div>
</article>

app/views/statics/about.html.erb
<article class="about">
<h1> About A K McCrate </h1>
<p>I'm Ashton. I'm a human being (family: Hominidae, genus: Homo, species: sapien). I am on a never-ending mission to myelinate my neurons. I am currently studying at Hacker School to advance my understanding of various computer technologies. I primarily work with Ruby, but am spending some time with JS, CS theory, and what ever else proves to be captivating.</p>
<p>My interests include logic, sense of place, flow, and pushing the boundary. My goal is to create instances that incorporate elements of each.</p>
<h1>Get In Touch</h1>
<p>Email: <a href="mailto:frontdesk@akmccrate.com">frontdesk@akmccrate.com</a></p>
<p>Twitter: <a href="http://twitter.com/akmccrate">@akmccrate</a></p>
<p>Github: <a href="https://github.com/akmcc">akmcc</a></p>
</article>